# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34d97e3217b797d8530a272f0f8d638b698e5cf158ec8eedccad4b483ac4f1421a899e412a2a26d9bcf377f90936f568e6581734a85d9702aa11210c252b537a

test:
  secret_key_base: 17d06832a258fc1360ce6994597ec9f9f12825733744149488bde812256fe7946866556ff619cdeedb29057077e6e3bd63af64ef9ae31af5e0cc4085fc394c34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
